name: Check PHPUnit tests

on:
  pull_request:
    branches: [ "main" ]
  merge_group:
    types: [ checks_requested ]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-22.04
    steps:

      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: >-
            dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite,
            bcmath, soap, intl, gd, exif, iconv
          coverage: none

      - name: Update package list
        run: sudo apt-get update

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-suggest

      - name: Create .env file
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Install npm dependencies
        run: npm install

      - name: Build Vite assets
        run: npm run build

      - name: Start dev server in background
        run: php artisan serve &

      - name: Storage Permission
        run: chmod -R 777 storage bootstrap/cache

      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ':memory:'
        run: ./vendor/bin/phpunit
