name: PHP Testsuite

on:
  pull_request:
    branches: [ "main" ]
  merge_group:
    types: [ checks_requested ]

jobs:
  tests:
    name: Run Testsuite
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none
          tools: composer:v2

      # Cache Composer dependencies
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      # Cache npm dependencies
      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install Composer Dependencies
        run: composer install -n --prefer-dist --no-progress

      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Prepare Testing Env
        run: |
          sed -i 's/DB_CONNECTION=.*/DB_CONNECTION=sqlite/' .env
          sed -i 's/DB_DATABASE=.*/DB_DATABASE=:memory:/' .env
          sed -i 's/REDIS_HOST=.*/REDIS_HOST=localhost/' .env
          sed -i 's/REDIS_PORT=.*/REDIS_PORT=6379/' .env
          sed -i 's/REDIS_CLIENT=.*/REDIS_CLIENT=predis/' .env

      - name: Install and Build Frontend Assets
        run: |
          npm ci
          npm run build

      - name: Run Testsuite
        run: php artisan test
